---
knx:
  gateway_ip: 172.17.0.198
  gateway_port: 3671
influxdb:
  host: influxdb
  # username: influknx
  # password: influknx
  database: influknx

datapoints:
  '7/0/0':
    description: 'Haus (Wirkleistung)'
    type: '4Byte'
    measurement: power
  '7/0/1':
    description: 'Wohnung (Wirkleistung)'
    type: '4Byte'
    measurement: power
  '7/0/2':
    description: 'Heizung (Wirkleistung)'
    type: '4Byte'
    measurement: power
  '7/0/4':
    description: 'PV (Wirkleistung)'
    type: '4Byte'
    measurement: power
  '7/0/10':
    description: 'Haus (Wirkenergie)'
    type: '4ByteUint'
    measurement: energy
  '7/0/11':
    description: 'Wohnung (Wirkenergie)'
    type: '4ByteUint'
    measurement: energy
  '7/0/12':
    description: 'Heizung (Wirkenergie)'
    type: '4ByteUint'
    measurement: energy
  '7/0/14':
    description: 'PV (Wirkenergie)'
    type: '4ByteUint'
    measurement: energy
  '7/0/20':
    description: 'Haus (Wirkenergie, T1)'
    type: '4ByteUint'
    measurement: energy
  '7/0/21':
    description: 'Haus (Wirkenergie, T2)'
    type: '4ByteUint'
    measurement: energy
  '7/0/22':
    description: 'Wohnung (Wirkenergie, T1)'
    type: '4ByteUint'
    measurement: energy
  '7/0/23':
    description: 'Wohnung (Wirkenergie, T2)'
    type: '4ByteUint'
    measurement: energy
  '7/0/24':
    description: 'PV (Wirkenergie, T1)'
    type: '4ByteUint'
    measurement: energy
  '7/0/25':
    description: 'PV (Wirkenergie, T2)'
    type: '4ByteUint'
    measurement: energy
  '7/0/26':
    description: 'Heizung (Wirkenergie, T1)'
    type: '4ByteUint'
    measurement: energy
  '7/0/27':
    description: 'Heizung (Wirkenergie, T2)'
    type: '4ByteUint'
    measurement: energy
sources:
  '1.0.131': 'Z채hler Haus'
  '1.0.133': 'Z채hler Heizung'
  '1.0.134': 'Z채hler PV'
  '1.0.132': 'Z채hler Wohung'
