---
version: '2'

services:
  influxdb:
    image: influxdb
    volumes:
      - 'influxdb:/var/lib/influxdb'
    ports:
      - "8086:8086"
    restart: always
    user: '65001'
    environment:
      INFLUXDB_DB: influknx
  influknx:
    image: influknx:devel
    volumes:
      - '/vagrant/config.yml:/usr/src/app/config.yml'
    links:
      - 'influxdb:influxdb'
  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    volumes:
      - 'grafana:/var/lib/grafana'
    links:
      - 'influxdb:influxdb'
    environment:
      GF_SECURITY_ADMIN_PASSWORD: secret
volumes:
  grafana:
  influxdb:
